wandb_version: 1

# Example variables below. Uncomment (remove leading '# ') to use them, or just
# delete and create your own.

epochs:
  desc: Number of epochs to train over
  value: 10
hidden_nodes:
  desc: Size of the hidden layer
  value: 100
